// <auto-generated />
#nullable enable annotations
namespace DomainMap.IntegrationTests.Mapper
{
    public static partial class CircularReferenceMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.CircularReferenceDto ToDto(global::DomainMap.IntegrationTests.Models.CircularReferenceObject obj)
        {
            return MapToCircularReferenceDto(
                obj,
                new global::DomainMap.Abstractions.ReferenceHandling.PreserveReferenceHandler()
            );
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        private static global::DomainMap.IntegrationTests.Dto.CircularReferenceDto MapToCircularReferenceDto(global::DomainMap.IntegrationTests.Models.CircularReferenceObject source, global::DomainMap.Abstractions.ReferenceHandling.IReferenceHandler refHandler)
        {
            if (refHandler.TryGetReference<global::DomainMap.IntegrationTests.Models.CircularReferenceObject, global::DomainMap.IntegrationTests.Dto.CircularReferenceDto>(source, out var existingTargetReference))
                return existingTargetReference;
            var target = new global::DomainMap.IntegrationTests.Dto.CircularReferenceDto();
            refHandler.SetReference<global::DomainMap.IntegrationTests.Models.CircularReferenceObject, global::DomainMap.IntegrationTests.Dto.CircularReferenceDto>(source, target);
            target.Value = source.Value;
            if (source.Parent != null)
            {
                target.Parent = MapToCircularReferenceDto(source.Parent, refHandler);
            }
            else
            {
                target.Parent = null;
            }
            return target;
        }
    }
}