// <auto-generated />
#nullable enable
namespace DomainMap.IntegrationTests.Mapper
{
    public partial class DerivedMapper2
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public sealed override partial long IntToLong(int value)
        {
            return (long)value;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public new partial string IntToString(int value)
        {
            return value.ToString();
        }
    }
}