// <auto-generated />
#nullable enable
namespace DomainMap.IntegrationTests.Mapper
{
    public partial class DerivedMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public override partial long IntToLong(int value)
        {
            return (long)value;
        }
    }
}