// <auto-generated />
#nullable enable annotations
namespace DomainMap.IntegrationTests.Mapper
{
    public partial class GenericUserMethodMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public partial global::DomainMap.IntegrationTests.Dto.DocumentDto MapDocument(global::DomainMap.IntegrationTests.Models.Document source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.DocumentDto(
                source.Title,
                MapUser(source.CreatedBy),
                MapOptional<global::DomainMap.IntegrationTests.Models.User, global::DomainMap.IntegrationTests.Dto.UserDto>(source.ModifiedBy)
            );
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        private partial TTarget Map<TSource, TTarget>(TSource source) where TSource : notnull where TTarget : notnull
        {
            return source switch
            {
                global::DomainMap.IntegrationTests.Models.Document x when typeof(TTarget).IsAssignableFrom(typeof(global::DomainMap.IntegrationTests.Dto.DocumentDto)) => (TTarget)(object)MapDocument(x),
                global::DomainMap.IntegrationTests.Models.User x when typeof(TTarget).IsAssignableFrom(typeof(global::DomainMap.IntegrationTests.Dto.UserDto)) => (TTarget)(object)MapUser(x),
                global::DomainMap.IntegrationTests.Models.AssemblyScopedModel x when typeof(TTarget).IsAssignableFrom(typeof(global::DomainMap.IntegrationTests.Dto.AssemblyScopedDto)) => (TTarget)(object)global::DomainMap.IntegrationTests.Mapper.AssemblyScopedMappers.ToDto(x),
                _ => throw new global::System.ArgumentException($"Cannot map {source.GetType()} to {typeof(TTarget)} as there is no known type mapping", nameof(source)),
            };
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        private partial global::DomainMap.IntegrationTests.Dto.UserDto MapUser(global::DomainMap.IntegrationTests.Models.User source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.UserDto(source.Name);
            return target;
        }
    }
}