// <auto-generated />
#nullable enable annotations
namespace DomainMap.IntegrationTests.Mapper
{
    public static partial class EnumMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Mapper.Enum2 Map(global::DomainMap.IntegrationTests.Mapper.Enum1 e)
        {
            return e switch
            {
                global::DomainMap.IntegrationTests.Mapper.Enum1.Value1 => global::DomainMap.IntegrationTests.Mapper.Enum2.Value1,
                global::DomainMap.IntegrationTests.Mapper.Enum1.Value2 => global::DomainMap.IntegrationTests.Mapper.Enum2.Value2,
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(e), e, "The value of enum Enum1 is not supported"),
            };
        }
    }
}