// <auto-generated />
#nullable enable annotations
namespace DomainMap.IntegrationTests.Mapper
{
    public static partial class NamedMappings
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.NamedMappingValuesDto MapWithNamedMappings(global::DomainMap.IntegrationTests.Models.NamedMappingObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.NamedMappingValuesDto();
            target.FromMapValue = StringValueBuilder();
            target.FromMapPropertyUse = ModifyValue(source.SourceValue);
            target.FromMapPropertyFromSource = UseSource(source);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial void UpdateDto(global::DomainMap.IntegrationTests.Models.NamedMappingObject source, global::DomainMap.IntegrationTests.Dto.NamedMappingValuesDto target)
        {
            target.FromMapValue = StringValueBuilder();
            target.FromMapPropertyUse = ModifyValue(source.SourceValue);
            target.FromMapPropertyFromSource = UseSource(source);
        }
    }
}