// <auto-generated />
#nullable enable
namespace DomainMap.IntegrationTests.Mapper
{
    public static partial class NullableDisabledMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull(nameof(src))]
        public static partial global::DomainMap.IntegrationTests.Mapper.NullableDisabledMapper.MyDto? Map(this global::DomainMap.IntegrationTests.Mapper.NullableDisabledMapper.MyClass? src)
        {
            if (src == null)
                return default;
            var target = new global::DomainMap.IntegrationTests.Mapper.NullableDisabledMapper.MyDto();
            target.StringValue = src.StringValue;
            target.IntValue = src.IntValue;
            target.Nested = MapNested(src.Nested);
            return target;
        }
    }
}