// <auto-generated />
#nullable enable
namespace DomainMap.IntegrationTests.Mapper
{
    public static partial class StackDeepCloningMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::System.Collections.Generic.Stack<int> Copy(global::System.Collections.Generic.Stack<int> src)
        {
            return new global::System.Collections.Generic.Stack<int>(global::System.Linq.Enumerable.Reverse(src));
        }
    }
}