// <auto-generated />
#nullable enable annotations
namespace DomainMap.IntegrationTests.Mapper
{
    public static partial class UseExternalMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.IdObjectDto Map(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::DomainMap.IntegrationTests.Mapper.UseExternalMapper.MyOtherMapper.MapInt(source.IdValue);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.IdObjectDto MapExternal(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::DomainMap.IntegrationTests.Mapper.ExternalMapperMethods.MapStatic(source.IdValue);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.IdObjectDto MapFromSourceExternal(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::DomainMap.IntegrationTests.Mapper.ExternalMapperMethods.ComputeSumStatic(source);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.IdObjectDto ConstantMapExternal(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::DomainMap.IntegrationTests.Mapper.ExternalMapperMethods.IntValueStatic();
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.IdObjectDto MapExternalString(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::DomainMap.IntegrationTests.Mapper.ExternalMapperMethods.MapStatic(source.IdValue);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.IdObjectDto MapFromSourceExternalString(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::DomainMap.IntegrationTests.Mapper.ExternalMapperMethods.ComputeSumStatic(source);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.IdObjectDto ConstantMapExternalString(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = global::DomainMap.IntegrationTests.Mapper.ExternalMapperMethods.IntValueStatic();
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial global::DomainMap.IntegrationTests.Dto.ExternalItemsDto ToDto(global::DomainMap.IntegrationTests.Models.ExternalItemsModel obj)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.ExternalItemsDto();
            if (obj.Item != null)
            {
                target.Item = global::DomainMap.IntegrationTests.Mapper.AssemblyScopedMappers.ToDto(obj.Item);
            }
            else
            {
                target.Item = null;
            }
            return target;
        }
    }
}
