// <auto-generated />
#nullable enable annotations
namespace DomainMap.IntegrationTests.Mapper
{
    public partial class UseExternalInstanceMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public partial global::DomainMap.IntegrationTests.Dto.IdObjectDto Map(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = _myOtherMapper.MapInt(source.IdValue);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public partial global::DomainMap.IntegrationTests.Dto.IdObjectDto MapExternalWithString(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = _externalMapper.MapInstance(source.IdValue);
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public partial global::DomainMap.IntegrationTests.Dto.IdObjectDto ConstantMapExternalWithString(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = _externalMapper.IntValueInstance();
            return target;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public partial global::DomainMap.IntegrationTests.Dto.IdObjectDto MapFromSourceExternalWithString(global::DomainMap.IntegrationTests.Models.IdObject source)
        {
            var target = new global::DomainMap.IntegrationTests.Dto.IdObjectDto();
            target.IdValue = _externalMapper.ComputeSumInstance(source);
            return target;
        }
    }
}