// <auto-generated />
#nullable enable
namespace DomainMap.IntegrationTests.Mapper
{
    public static partial class UseUserMethodWithRef
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        public static partial void Merge(global::DomainMap.IntegrationTests.Models.ArrayObject target, global::DomainMap.IntegrationTests.Models.ArrayObject second)
        {
            var targetRef = target.IntArray;
            MapArray(ref targetRef, second.IntArray);
            target.IntArray = targetRef;
        }
    }
}