using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DomainMapper.Engine;

internal sealed partial class MapperCompiler
{
    private string EmitSource()
    {
        var writer = new SourceWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");

        var namespaceName = _mapperType.ContainingNamespace.IsGlobalNamespace ? null : _mapperType.ContainingNamespace.ToDisplayString();
        if (namespaceName != null)
        {
            writer.Line($"namespace {namespaceName}");
            writer.Line("{");
            writer.Indent();
        }

        var typeHierarchy = GetTypeHierarchy(_mapperType).ToArray();
        foreach (var type in typeHierarchy)
        {
            writer.Line(BuildTypeDeclaration(type));
            writer.Line("{");
            writer.Indent();
        }

        var contracts = _rootContracts.Concat(_helperContracts).ToArray();
        for (var index = 0; index < contracts.Length; index++)
        {
            EmitContract(writer, contracts[index]);
            if (index < contracts.Length - 1)
                writer.Line();
        }

        if (contracts.Length > 0 && _supportMembers.Count > 0)
            writer.Line();
        for (var index = 0; index < _supportMembers.Count; index++)
        {
            foreach (var line in _supportMembers[index].Split('\n'))
                writer.Line(line);
            if (index < _supportMembers.Count - 1)
                writer.Line();
        }

        foreach (var _ in typeHierarchy)
        {
            writer.Unindent();
            writer.Line("}");
        }

        if (namespaceName != null)
        {
            writer.Unindent();
            writer.Line("}");
        }

        return writer.ToString();
    }

    private static void EmitContract(SourceWriter writer, MappingContract contract)
    {
        writer.Line(GeneratedCodeAttribute);
        writer.Line(contract.Declaration);
        writer.Line("{");
        writer.Indent();
        foreach (var line in contract.Body.Split('\n'))
        {
            writer.Line(line);
        }

        writer.Unindent();
        writer.Line("}");
    }

    private string BuildDeclaration(IMethodSymbol method)
    {
        var modifiers = new List<string> { AccessibilityText(method.DeclaredAccessibility) };
        if (HasExplicitNewModifier(method))
            modifiers.Add("new");
        if (method.IsStatic)
            modifiers.Add("static");
        else
        {
            if (method.IsSealed)
                modifiers.Add("sealed");
            if (method.IsOverride)
                modifiers.Add("override");
            else if (method.IsVirtual)
                modifiers.Add("virtual");
        }
        if (RequiresUnsafeModifier(method))
            modifiers.Add("unsafe");
        modifiers.Add("partial");

        var typeParameters = TypeParameters(method.TypeParameters);
        var parameters = string.Join(", ", method.Parameters.Select(ParameterDeclaration));
        var constraints = ConstraintClauses(method.TypeParameters);
        return $"{string.Join(" ", modifiers)} {TypeName(method.ReturnType)} {Escape(method.Name)}{typeParameters}({parameters}){constraints}";
    }

    private static bool HasExplicitNewModifier(IMethodSymbol method) =>
        method.DeclaringSyntaxReferences.Any(x =>
            x.GetSyntax() is MethodDeclarationSyntax declaration && declaration.Modifiers.Any(SyntaxKind.NewKeyword)
        );

    private static string ParameterDeclaration(IParameterSymbol parameter)
    {
        var modifiers = new List<string>();
        if (parameter.IsThis)
            modifiers.Add("this");
        if (parameter.ScopedKind != ScopedKind.None)
            modifiers.Add("scoped");
        if (parameter.IsParams)
            modifiers.Add("params");
        modifiers.Add(
            parameter.RefKind switch
            {
                RefKind.Ref => "ref",
                RefKind.Out => "out",
                RefKind.In => "in",
                RefKind.RefReadOnlyParameter => "ref readonly",
                _ => string.Empty,
            }
        );
        var prefix = string.Join(" ", modifiers.Where(x => x.Length > 0));
        return $"{(prefix.Length == 0 ? string.Empty : prefix + " ")}{TypeName(parameter.Type)} {Escape(parameter.Name)}";
    }

    private static string BuildTypeDeclaration(INamedTypeSymbol type)
    {
        var modifiers = new List<string> { AccessibilityText(type.DeclaredAccessibility) };
        if (type.IsStatic)
            modifiers.Add("static");
        else if (type.TypeKind == TypeKind.Class)
        {
            if (type.IsAbstract)
                modifiers.Add("abstract");
            if (type.IsSealed)
                modifiers.Add("sealed");
        }
        else if (type.TypeKind == TypeKind.Struct)
        {
            if (type.IsReadOnly)
                modifiers.Add("readonly");
            if (type.IsRefLikeType)
                modifiers.Add("ref");
        }
        modifiers.Add("partial");
        modifiers.Add(
            type switch
            {
                { IsRecord: true, TypeKind: TypeKind.Struct } => "record struct",
                { IsRecord: true } => "record",
                { TypeKind: TypeKind.Struct } => "struct",
                { TypeKind: TypeKind.Interface } => "interface",
                _ => "class",
            }
        );
        return $"{string.Join(" ", modifiers)} {Escape(type.Name)}{TypeParameters(type.TypeParameters)}{ConstraintClauses(type.TypeParameters)}";
    }

    private static IEnumerable<INamedTypeSymbol> GetTypeHierarchy(INamedTypeSymbol type)
    {
        var stack = new Stack<INamedTypeSymbol>();
        for (var current = type; current != null; current = current.ContainingType)
        {
            stack.Push(current);
        }
        return stack;
    }

    private static string TypeParameters(ImmutableArray<ITypeParameterSymbol> typeParameters) =>
        typeParameters.Length == 0 ? string.Empty : $"<{string.Join(", ", typeParameters.Select(x => $"{Variance(x)}{Escape(x.Name)}"))}>";

    private static string Variance(ITypeParameterSymbol typeParameter) =>
        typeParameter.Variance switch
        {
            VarianceKind.In => "in ",
            VarianceKind.Out => "out ",
            _ => string.Empty,
        };

    private static string ConstraintClauses(ImmutableArray<ITypeParameterSymbol> typeParameters)
    {
        var clauses = new List<string>();
        foreach (var typeParameter in typeParameters)
        {
            var constraints = new List<string>();
            if (typeParameter.HasUnmanagedTypeConstraint)
                constraints.Add("unmanaged");
            else if (typeParameter.HasValueTypeConstraint)
                constraints.Add("struct");
            else if (typeParameter.HasReferenceTypeConstraint)
                constraints.Add(
                    typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class"
                );
            else if (typeParameter.HasNotNullConstraint)
                constraints.Add("notnull");

            constraints.AddRange(typeParameter.ConstraintTypes.Select(TypeName));
            if (typeParameter.HasConstructorConstraint)
                constraints.Add("new()");
            if (constraints.Count > 0)
                clauses.Add($"where {Escape(typeParameter.Name)} : {string.Join(", ", constraints)}");
        }
        return clauses.Count == 0 ? string.Empty : " " + string.Join(" ", clauses);
    }

    private static bool RequiresUnsafeModifier(IMethodSymbol method) =>
        method.ReturnType.TypeKind == TypeKind.Pointer || method.Parameters.Any(x => x.Type.TypeKind == TypeKind.Pointer);

    private bool ReserveHelper(string key, string baseName, out string helperName)
    {
        if (_helperNames.TryGetValue(key, out helperName!))
            return false;

        helperName = baseName;
        var suffix = 2;
        while (!_usedHelperNames.Add(helperName))
        {
            helperName = $"{baseName}{suffix}";
            suffix++;
        }
        _helperNames.Add(key, helperName);
        return true;
    }

    private string ReserveMemberName(string baseName)
    {
        var memberName = baseName;
        var suffix = 2;
        while (!_usedHelperNames.Add(memberName))
        {
            memberName = $"{baseName}{suffix}";
            suffix++;
        }
        return memberName;
    }

    private string EnsureReferenceKey()
    {
        if (_referenceKeyName != null)
            return _referenceKeyName;

        _referenceKeyName = ReserveMemberName("__DomainMapperReferenceKey");

        _supportMembers.Add(
            $"private readonly struct {_referenceKeyName} : global::System.IEquatable<{_referenceKeyName}>\n"
                + "{\n"
                + "    private readonly object _source;\n"
                + "    private readonly global::System.Type _targetType;\n"
                + $"    internal {_referenceKeyName}(object source, global::System.Type targetType) {{ _source = source; _targetType = targetType; }}\n"
                + $"    public bool Equals({_referenceKeyName} other) => global::System.Object.ReferenceEquals(_source, other._source) && _targetType == other._targetType;\n"
                + $"    public override bool Equals(object? value) => value is {_referenceKeyName} other && Equals(other);\n"
                + "    public override int GetHashCode() { unchecked { return (global::System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(_source) * 397) ^ _targetType.GetHashCode(); } }\n"
                + "}"
        );
        return _referenceKeyName;
    }

    private static string BuildHelperKey(ITypeSymbol sourceType, ITypeSymbol targetType, MappingContext context)
    {
        var typeParameters = string.Join(",", context.MethodTypeParameters.Select(x => x.ToDisplayString(TypeDisplayFormat)));
        var constraints = ConstraintClauses(context.MethodTypeParameters);
        var ambientValues = string.Join(",", context.AmbientValues.Select(x => $"{x.Name}:{TypeName(x.Type)}"));
        var depth = context.Configuration?.MaximumDepth?.ToString(CultureInfo.InvariantCulture) ?? "none";
        var configurationIdentity =
            context.Configuration == null
                ? "convention"
                : $"{context.Configuration.Method.ToDisplayString()}@{context.Configuration.Method.Locations.FirstOrDefault()?.SourceSpan.Start ?? -1}"
                    + $"|depth-behavior:{context.Configuration.DepthExhaustionBehavior}";
        var references = context.Configuration?.PreserveReferences == true ? "tracked" : "untracked";
        return $"{TypeName(sourceType)}->{TypeName(targetType)}|<{typeParameters}>{constraints}|{ambientValues}|depth:{depth}|references:{references}|{configurationIdentity}";
    }

    private string BuildHelperDeclaration(ITypeSymbol targetType, string helperName, ITypeSymbol sourceType, MappingContext context)
    {
        var parameters = new List<string> { $"{TypeName(sourceType)} source" };
        parameters.AddRange(context.AmbientValues.Select((value, index) => $"{TypeName(value.Type)} __ambient{index}"));
        if (context.Configuration?.PreserveReferences == true)
            parameters.Add($"global::System.Collections.Generic.Dictionary<{EnsureReferenceKey()}, object> __references");
        if (context.Configuration?.MaximumDepth != null)
            parameters.Add("int __depth");
        return $"private static {TypeName(targetType)} {Escape(helperName)}{TypeParameters(context.MethodTypeParameters)}({string.Join(", ", parameters)}){ConstraintClauses(context.MethodTypeParameters)}";
    }

    private static string BuildHelperCall(string helperName, string sourceExpression, MappingContext context)
    {
        var typeArguments =
            context.MethodTypeParameters.Length == 0
                ? string.Empty
                : $"<{string.Join(", ", context.MethodTypeParameters.Select(x => Escape(x.Name)))}>";
        var arguments = new[] { sourceExpression }.Concat(context.AmbientValues.Select(x => x.Expression));
        if (context.Configuration?.PreserveReferences == true)
            arguments = arguments.Append("__references");
        if (context.Configuration?.MaximumDepth != null)
        {
            var depth = context.IsHelper
                ? "__depth - 1"
                : (context.Configuration.MaximumDepth.Value - (context.Configuration.PreserveReferences ? 0 : 1)).ToString(
                    CultureInfo.InvariantCulture
                );
            arguments = arguments.Append(depth);
        }
        return $"{Escape(helperName)}{typeArguments}({string.Join(", ", arguments)})";
    }

    private static string BuildHintName(INamedTypeSymbol mapperType)
    {
        var identity = mapperType.ToDisplayString(TypeDisplayFormat);
        return $"{Sanitize(identity)}_{StableHash(identity):X8}.g.cs";
    }

    private static uint StableHash(string value)
    {
        const uint offset = 2166136261;
        const uint prime = 16777619;
        var hash = offset;
        foreach (var character in value)
        {
            hash ^= character;
            hash *= prime;
        }
        return hash;
    }

    private static string AccessibilityText(Accessibility accessibility) =>
        accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal",
        };

    private static string Escape(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : $"@{identifier}";

    private static string Sanitize(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            if (char.IsLetterOrDigit(character) || character == '_')
                builder.Append(character);
        }
        return builder.Length == 0 ? "Mapping" : builder.ToString();
    }
}
