<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.2.3-dev</Version>
    <Authors>DomainMapper Contributors</Authors>
    <!-- release environment constants -->
    <DefineConstants Condition="'$(DOMAINMAPPER_ENVIRONMENT)' == 'next'">$(DefineConstants);ENV_NEXT</DefineConstants>
    <DefineConstants Condition="'$(DOMAINMAPPER_ENVIRONMENT)' == 'stable'">$(DefineConstants);ENV_STABLE</DefineConstants>
    <DefineConstants Condition="'$(DOMAINMAPPER_ENVIRONMENT)' == ''">$(DefineConstants);ENV_LOCAL</DefineConstants>
  </PropertyGroup>
</Project>
