//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    private partial void Map(global::System.Collections.Generic.List<global::A>? source, global::RepeatedField<global::B> target)
    {
        if (source == null)
            return;
        for (var i = 0; i < source.Count; i++)
        {
            var item = source[i];
            target.Add(MapToB(item));
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    private global::B MapToB(global::A source)
    {
        var target = new global::B();
        target.Value = source.Value;
        return target;
    }
}