//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    private partial void Map<TSource, TTarget>(TSource source, TTarget target)
    {
        if (source == null || target == null)
            return;
        throw new global::System.NotImplementedException("DomainMap: Could not generate mapping");
    }
}