//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    partial global::B MapBase(global::A a)
    {
        var target = new global::B();
        target.DestinationName = a.SourceName;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    partial global::B MapFirst(global::A a)
    {
        var target = new global::B();
        target.DestinationName = a.SourceName;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    partial global::B MapSecond(global::A a)
    {
        var target = new global::B();
        target.DestinationName = a.SourceName;
        return target;
    }
}