//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private partial global::B MapOther(global::A source)
    {
        var target = new global::B();
        target.Value = source;
        return target;
    }

    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public partial global::B Map(global::A source)
    {
        var target = new global::B();
        target.Value = source;
        return target;
    }
}