//HintName: FooBarMapper.g.cs
// <auto-generated />
#nullable enable
namespace Test.A
{
    internal partial class FooBarMapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal partial string FooToBar(string value)
        {
            return value;
        }
    }
}