//HintName: CarFeature.Mappers.CarMapper.g.cs
// <auto-generated />
#nullable enable
namespace FooBar
{
    public static partial class CarFeature
    {
        public static partial class Mappers
        {
            public partial class CarMapper
            {
                [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                public partial double ToDouble(int value)
                {
                    return (double)value;
                }
            }
        }
    }
}