//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
namespace MapperNamespace
{
    public partial class Mapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static partial global::MapperNamespace.B Map(global::MapperNamespace.A source)
        {
            var target = new global::MapperNamespace.B(source.Value);
            return target;
        }
    }
}