//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
namespace MapperNamespace
{
    public partial class Mapper
    {
        [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
        private static partial global::MapperNamespace.B Map(global::MapperNamespace.A source)
        {
            var target = new global::MapperNamespace.B(global::OtherNamespace.OtherMapper.ModifyString(source.Value));
            return target;
        }
    }
}