//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    partial global::B Map(global::A source)
    {
        var target = new global::B();
        target.GetValue() = source.GetValue();
        return target;
    }
}

[global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
static file class AAccessor
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "value")]
    public static extern ref int GetValue(this global::A target);
}

[global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
static file class BAccessor
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    [global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Field, Name = "value")]
    public static extern ref int GetValue(this global::B target);
}