//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    partial global::B Map(global::A src, int value, int id)
    {
        var target = new global::B()
        {
            Value = value.ToString(),
            Id = id,
        };
        target.StringValue = src.StringValue;
        return target;
    }
}