//HintName: BaseMapper.g.cs
// <auto-generated />
#nullable enable
public partial class BaseMapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("DomainMap", "0.0.1.0")]
    protected partial void MyIntToDoubleMapping(global::System.Collections.Generic.List<int> src, global::System.Collections.Generic.List<double> dst)
    {
        dst.EnsureCapacity(src.Count + dst.Count);
        for (var i = 0; i < src.Count; i++)
        {
            var item = src[i];
            dst.Add((double)item);
        }
    }
}