<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
  <ItemGroup Condition="'$(DomainMapperNugetPackageVersion)' == ''">
    <ProjectReference Include="..\..\src\DomainMapper\DomainMapper.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference
      Include="..\..\src\DomainMapper.Abstractions\DomainMapper.Abstractions.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="true"
    />
  </ItemGroup>
  <!-- In the CI pipeline, we always want to use test the prebuilt nuget package version, since that nuget package will then be distributed -->
  <ItemGroup Condition="'$(DomainMapperNugetPackageVersion)' != ''">
    <PackageReference Include="DomainMapper" Version="$(DomainMapperNugetPackageVersion)" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
</Project>
