name: docs

on:
  workflow_call:
    inputs:
      deploy:
        required: false
        type: boolean
        default: false
      environment:
        required: false
        type: string
        default: 'next'
      version:
        required: false
        type: string
        default: '1.1.0-dev'
  workflow_dispatch:
    inputs:
      deploy:
        required: false
        type: boolean
        default: true
        description: A boolean indicating whether the built pages should be deployed
      environment:
        required: false
        type: choice
        default: 'next'
        options:
          - next
          - stable
        description: The github deployment which is targeted, gets prefixed by 'docs-'
      version:
        required: false
        type: string
        default: '1.1.0-dev'
        description: The version of DomainMapper to be referenced from the documentation
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: echo "building ${{ inputs.version }} for ${{ inputs.environment }}"
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v5
      - run: dotnet tool restore
      - run: dotnet build
      - uses: actions/setup-node@v6
        with:
          node-version-file: './docs/.node-version'
      - run: npm ci
        working-directory: ./docs
      - run: npm run build
        working-directory: ./docs
        env:
          DOMAINMAPPER_VERSION: ${{ inputs.version }}
          ENVIRONMENT: ${{ inputs.environment }}
          DOCUSAURUS_URL: ${{ inputs.environment == 'stable' && 'https://skuirrels.github.io' || '' }}
          DOCUSAURUS_BASE_URL: ${{ inputs.environment == 'stable' && '/DomainMapper/' || '/' }}
      # run lint after build, as generated files may be imported which cannot be found otherwise
      - run: npm run lint
        working-directory: ./docs
      - uses: actions/upload-artifact@v7
        with:
          name: domainmapper-docs
          path: 'docs/build'
      - name: Upload stable site for GitHub Pages
        if: ${{ inputs.deploy && inputs.environment == 'stable' }}
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'docs/build'
  deploy:
    if: ${{ inputs.deploy && inputs.environment == 'stable' }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    runs-on: ubuntu-latest
    needs: build
    steps:
      # we never want to deploy with no version set
      # stop the deployment here
      - name: Version not set
        if: ${{ inputs.version == '' || inputs.version == '1.1.0-dev' }}
        run: exit 1
      - uses: actions/deploy-pages@v5
        id: deployment
